# Generated by Django 4.1.6 on 2023-02-06 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alljob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 2, 6, 6, 49, 18, 610521))),
                ('content', models.CharField(max_length=50)),
                ('done', models.CharField(default='n', max_length=1)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
