# Generated by Django 4.1.6 on 2023-02-06 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alluser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('online', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='alljob',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 7, 18, 57, 31273)),
        ),
    ]
